export const foodsName = [
	"Arroz",
	"Maçã",
	"Sorvete",
	"Pão",
	"Pizza",
	"Hamburger",
	"Sushi",
	"Espaguete",
	"Coxinha",
	"Acarajé",
	"Feijoada",
	"Tapioca",
	"Churrasco",
	"Lasanha",
	"Croissant",
	"Tomate",
	"Chocolate",
	"Batata",
	"Bolo de Cenoura",
	"Tacos",
	"Guacamole",
];

export const foodsQuestions = [
	"Você gosta dessa comida?",
	"Esta comida é geralmente servida como entrada, prato principal ou sobremesa?",
	"Esta comida é associada a algum país ou região específica?",
	"Você costuma comer isso em algum evento especial?",
	"Esta comida é cozida, assada ou frita?",
	"Você normalmente come isso com as mãos ou precisa de utensílios?",
	"Esta comida é considerada saudável?",
	"Esta comida é comumente consumida no café da manhã, almoço ou jantar?",
	"Esta comida pode ser encontrada em um restaurante fast food?",
	"Esta comida é típica de alguma festividade?",
	"Esta comida é tradicionalmente consumida quente ou fria?",
	"Esta comida é melhor descrita como leve ou pesada?",
	"Esta comida é popular em alguma estação do ano específica?",
	"Qual é o método de preparo principal desta comida?",
	"Esta comida é tipicamente servida para quantas pessoas?",
	"Esta comida é popular em piqueniques ou acampamentos?",
	"Você costuma adicioná-la em outras receitas como ingrediente?",
	"Esta já comeu essa comida com algum tipo de molho?",
	"Você come essa comida com frequencia?",
	"Esta comida normalmente é cara ou barata?",
	"Esta dura muito na geladeira?",
	"Você normalmente come esta comida pura ou com outros ingredientes",
	"Você comeria esta comida antes de fazer uma atividade física?",
];
